name: tariff_calc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  xml2json: ^6.2.6
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
flutter:
  uses-material-design: true

  assets:
    - .env